# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\edit_ship_loc.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_edit_ship_loc_dialog(object):
    def setupUi(self, edit_ship_loc_dialog):
        edit_ship_loc_dialog.setObjectName("edit_ship_loc_dialog")
        edit_ship_loc_dialog.setWindowModality(QtCore.Qt.NonModal)
        edit_ship_loc_dialog.resize(550, 350)
        edit_ship_loc_dialog.setMinimumSize(QtCore.QSize(550, 350))
        edit_ship_loc_dialog.setMaximumSize(QtCore.QSize(550, 350))
        self.gridLayout = QtWidgets.QGridLayout(edit_ship_loc_dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(edit_ship_loc_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.current_loc = QtWidgets.QLabel(edit_ship_loc_dialog)
        self.current_loc.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.current_loc.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.current_loc.setText("")
        self.current_loc.setObjectName("current_loc")
        self.gridLayout_2.addWidget(self.current_loc, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 3, 0, 1, 3)
        self.table = QtWidgets.QTableWidget(edit_ship_loc_dialog)
        self.table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table.setObjectName("table")
        self.table.setColumnCount(3)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        self.table.horizontalHeader().setDefaultSectionSize(125)
        self.gridLayout.addWidget(self.table, 4, 0, 1, 3)
        self.label_dialog_inpoject = QtWidgets.QLabel(edit_ship_loc_dialog)
        self.label_dialog_inpoject.setObjectName("label_dialog_inpoject")
        self.gridLayout.addWidget(self.label_dialog_inpoject, 0, 0, 1, 3)
        self.cancel_button = QtWidgets.QPushButton(edit_ship_loc_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel_button.sizePolicy().hasHeightForWidth())
        self.cancel_button.setSizePolicy(sizePolicy)
        self.cancel_button.setObjectName("cancel_button")
        self.gridLayout.addWidget(self.cancel_button, 5, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        self.add_button = QtWidgets.QPushButton(edit_ship_loc_dialog)
        self.add_button.setEnabled(False)
        self.add_button.setObjectName("add_button")
        self.gridLayout.addWidget(self.add_button, 5, 1, 1, 1)
        self.line = QtWidgets.QFrame(edit_ship_loc_dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 3)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(edit_ship_loc_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        self.current_ship = QtWidgets.QLabel(edit_ship_loc_dialog)
        self.current_ship.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.current_ship.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.current_ship.setText("")
        self.current_ship.setObjectName("current_ship")
        self.gridLayout_4.addWidget(self.current_ship, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 2, 0, 1, 3)

        self.retranslateUi(edit_ship_loc_dialog)
        QtCore.QMetaObject.connectSlotsByName(edit_ship_loc_dialog)
        edit_ship_loc_dialog.setTabOrder(self.table, self.add_button)
        edit_ship_loc_dialog.setTabOrder(self.add_button, self.cancel_button)

    def retranslateUi(self, edit_ship_loc_dialog):
        _translate = QtCore.QCoreApplication.translate
        edit_ship_loc_dialog.setWindowTitle(_translate("edit_ship_loc_dialog", "Изменение место жительства студента"))
        self.label.setText(_translate("edit_ship_loc_dialog", "Текущее место жительства:"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("edit_ship_loc_dialog", "ID"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("edit_ship_loc_dialog", "Адрес"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("edit_ship_loc_dialog", "Район"))
        self.label_dialog_inpoject.setText(_translate("edit_ship_loc_dialog", "Выберете новое место жительства"))
        self.cancel_button.setText(_translate("edit_ship_loc_dialog", "Отмена"))
        self.add_button.setText(_translate("edit_ship_loc_dialog", "Изменить"))
        self.label_2.setText(_translate("edit_ship_loc_dialog", "ФИО студента"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    edit_ship_loc_dialog = QtWidgets.QDialog()
    ui = Ui_edit_ship_loc_dialog()
    ui.setupUi(edit_ship_loc_dialog)
    edit_ship_loc_dialog.show()
    sys.exit(app.exec_())

